// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Funcion_Configurar(lv_event_t * e);
void Funcion_Retornar_Llamado(lv_event_t * e);
void Funcion_Historial(lv_event_t * e);
void Funcion_Configura_Parmetros(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
