// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#ifndef _LLAMADOENFERMERIA_UI_H
#define _LLAMADOENFERMERIA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_plantilla_01_png);   // assets/Plantilla_01.png
LV_IMG_DECLARE( ui_img_espera_png);   // assets/Espera.png
LV_IMG_DECLARE( ui_img_gear_8248448_png);   // assets/gear_8248448.png
LV_IMG_DECLARE( ui_img_f_configura_png);   // assets/F_Configura.png
LV_IMG_DECLARE( ui_img_b_llamado_png);   // assets/B_Llamado.png
LV_IMG_DECLARE( ui_img_b_historial_png);   // assets/B_Historial.png
LV_IMG_DECLARE( ui_img_b_configuracion_png);   // assets/B_Configuracion.png

// FONTS
LV_FONT_DECLARE( ui_font_Montserrat160);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
