// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#include "esp_log.h"
#include "ui.h"
bool F_Configurar = false;
bool F_Retornar_Llamado = false;
bool F_Historial = false;
bool F_Configura_Parmetros = false;
bool F_Salir_Parametros = false;
bool F_Grabar_Parametros = false;

void Funcion_Configurar(lv_event_t *e) {
  ESP_LOGW("UI_EVENTS", "FLAG: F_Configurar set");
  F_Configurar = true;
}

void Funcion_Retornar_Llamado(lv_event_t *e) {
  ESP_LOGW("UI_EVENTS", "FLAG: F_Retornar_Llamado set");
  F_Retornar_Llamado = true;
}

void Funcion_Historial(lv_event_t *e) {
  ESP_LOGW("UI_EVENTS", "FLAG: F_Historial set");
  F_Historial = true;
}

void Funcion_Configura_Parmetros(lv_event_t *e) {
  ESP_LOGW("UI_EVENTS", "FLAG: F_Configura_Parmetros set");
  F_Configura_Parmetros = true;
}

void Funcion_Salir_Parametros(lv_event_t *e) {
  ESP_LOGW("UI_EVENTS", "FLAG: F_Salir_Parametros set");
  F_Salir_Parametros = true;
}

void Funcion_Grabar_Parametros(lv_event_t *e) {
  ESP_LOGW("UI_EVENTS", "FLAG: F_Grabar_Parametros set");
  F_Grabar_Parametros = true;
}
