// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#include "esp_log.h"
#include "ui.h"
bool F_Configurar = false;
bool F_Retornar_Llamado = false;
bool F_Historial = false;
bool F_Configura_Parmetros = false;
void Funcion_Configurar(lv_event_t *e) {
  ESP_LOGI("UI_EVENTS", "Funcion_Configurar triggered!");
  F_Configurar = true;
}

void Funcion_Retornar_Llamado(lv_event_t *e) {
  ESP_LOGI("UI_EVENTS", "Funcion_Retornar_Llamado triggered!");
  F_Retornar_Llamado = true;
}

void Funcion_Historial(lv_event_t *e) {
  ESP_LOGI("UI_EVENTS", "Funcion_Historial triggered!");
  F_Historial = true;
}

void Funcion_Configura_Parmetros(lv_event_t *e) {
  ESP_LOGI("UI_EVENTS", "Funcion_Configura_Parmetros triggered!");
  F_Configura_Parmetros = true;
}
