// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#include "esp_log.h"
#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;
lv_obj_t *ui_Label2 = NULL;
lv_obj_t *ui_Label3 = NULL;
lv_obj_t *ui_Label4 = NULL;
lv_obj_t *ui_Button1 = NULL;
lv_obj_t *ui_Label5 = NULL;
lv_obj_t *ui_Label6 = NULL;
lv_obj_t *ui_Label7 = NULL;
// event funtions
void ui_event_Button1(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);
  if (event_code == LV_EVENT_PRESSED || event_code == LV_EVENT_CLICKED ||
      event_code == LV_EVENT_RELEASED) {
    ESP_LOGI("UI_DEBUG", "Button1 Event: %d", (int)event_code);
  }

  if (event_code == LV_EVENT_CLICKED || event_code == LV_EVENT_RELEASED) {
    Funcion_Configurar(e);
  }
}

// build funtions

void ui_Screen2_screen_init(void) {
  ui_Screen2 = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_image_src(ui_Screen2, &ui_img_espera_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label2 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label2, -401);
  lv_obj_set_y(ui_Label2, -124);
  lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label2, "08:15");
  lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x20406A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label2, &ui_font_Montserrat160,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label3 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label3, -387);
  lv_obj_set_y(ui_Label3, -16);
  lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label3, "Jueves, 12 de Marzo de 2026");
  lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x020202),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label4 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label4, 92);
  lv_obj_set_y(ui_Label4, -151);
  lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label4, "HospitalSanJose");
  lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_24,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Button1 = lv_button_create(ui_Screen2);
  lv_obj_set_width(ui_Button1, 200);
  lv_obj_set_height(ui_Button1, 200);
  lv_obj_set_x(ui_Button1, 477);
  lv_obj_set_y(ui_Button1, -86);
  lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_radius(ui_Button1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_image_src(ui_Button1, &ui_img_gear_8248448_png,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label5 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label5, 93);
  lv_obj_set_y(ui_Label5, -110);
  lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label5, "Conectada");
  lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label6 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label6, 77);
  lv_obj_set_y(ui_Label6, 31);
  lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label6, "Insertada");
  lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Label7 = lv_label_create(ui_Screen2);
  lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_Label7, 77);
  lv_obj_set_y(ui_Label7, 72);
  lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
  lv_label_set_text(ui_Label7, "14.5 G/  16G");
  lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_24,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
  // Expandimos el área de toque 60px para que sea más fácil de acertar
  lv_obj_set_ext_click_area(ui_Button1, 60);
}

void ui_Screen2_screen_destroy(void) {
  if (ui_Screen2)
    lv_obj_del(ui_Screen2);

  // NULL screen variables
  ui_Screen2 = NULL;
  ui_Label2 = NULL;
  ui_Label3 = NULL;
  ui_Label4 = NULL;
  ui_Button1 = NULL;
  ui_Label5 = NULL;
  ui_Label6 = NULL;
  ui_Label7 = NULL;
}
