// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#include "../ui.h"

lv_obj_t *ui_Screen4 = NULL;lv_obj_t *ui_Slider1 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_Roller1 = NULL;lv_obj_t *ui_Roller2 = NULL;lv_obj_t *ui_Roller3 = NULL;lv_obj_t *ui_Roller4 = NULL;lv_obj_t *ui_Roller5 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Button5 = NULL;lv_obj_t *ui_Button6 = NULL;
// event funtions
void ui_event_Button5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      Funcion_Grabar_Parametros( e );
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      Funcion_Salir_Parametros( e );
}
}

// build funtions

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_image_src( ui_Screen4, &ui_img_fondohospital_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_image_opa(ui_Screen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Slider1 = lv_slider_create(ui_Screen4);
lv_slider_set_value( ui_Slider1, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_Slider1)==LV_SLIDER_MODE_RANGE ) lv_slider_set_start_value( ui_Slider1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Slider1, 422);
lv_obj_set_height( ui_Slider1, 39);
lv_obj_set_x( ui_Slider1, 369 );
lv_obj_set_y( ui_Slider1, -153 );
lv_obj_set_align( ui_Slider1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xB3B1B1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_blend_mode(ui_Slider1, LV_BLEND_MODE_ADDITIVE, LV_PART_KNOB| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Slider1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Slider1, lv_obj_get_style_pad_right(ui_Slider1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label8 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -313 );
lv_obj_set_y( ui_Label8, -256 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"HORA Y FECHA");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x070707), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Screen4);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 682);
lv_obj_set_height( ui_Container1, 454);
lv_obj_set_x( ui_Container1, -253 );
lv_obj_set_y( ui_Container1, 38 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Roller1 = lv_roller_create(ui_Container1);
lv_roller_set_options( ui_Roller1, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n28\n30\n31\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller1, 467);
lv_obj_set_width( ui_Roller1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller1, -286 );
lv_obj_set_y( ui_Roller1, -3 );
lv_obj_set_align( ui_Roller1, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller2 = lv_roller_create(ui_Container1);
lv_roller_set_options( ui_Roller2, "ENE\nFEB\nMAR\nABR\nMAY\nJUN\nJUL\nAGO\nSEP\nOCT\nNOV\nDIC", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller2, 465);
lv_obj_set_width( ui_Roller2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller2, -166 );
lv_obj_set_y( ui_Roller2, -3 );
lv_obj_set_align( ui_Roller2, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_Roller2, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller3 = lv_roller_create(ui_Container1);
lv_roller_set_options( ui_Roller3, "2026\n2027\n2028\n2029\n2030\n2031\n2032\n2033\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller3, 464);
lv_obj_set_width( ui_Roller3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller3, -16 );
lv_obj_set_y( ui_Roller3, -3 );
lv_obj_set_align( ui_Roller3, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_Roller3, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller4 = lv_roller_create(ui_Container1);
lv_roller_set_options( ui_Roller4, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller4, 463);
lv_obj_set_width( ui_Roller4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller4, 109 );
lv_obj_set_y( ui_Roller4, -3 );
lv_obj_set_align( ui_Roller4, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_Roller4, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller5 = lv_roller_create(ui_Container1);
lv_roller_set_options( ui_Roller5, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n28\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller5, 466);
lv_obj_set_width( ui_Roller5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_Roller5, 211 );
lv_obj_set_y( ui_Roller5, -3 );
lv_obj_set_align( ui_Roller5, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_Roller5, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 354 );
lv_obj_set_y( ui_Label9, -268 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"VOLUMEN");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x0290FB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 367 );
lv_obj_set_y( ui_Label10, -79 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"0 %");
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button5 = lv_button_create(ui_Screen4);
lv_obj_set_width( ui_Button5, 100);
lv_obj_set_height( ui_Button5, 100);
lv_obj_set_x( ui_Button5, 250 );
lv_obj_set_y( ui_Button5, 135 );
lv_obj_set_align( ui_Button5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button5, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_Button5, &ui_img_2_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Button6 = lv_button_create(ui_Screen4);
lv_obj_set_width( ui_Button6, 100);
lv_obj_set_height( ui_Button6, 100);
lv_obj_set_x( ui_Button6, 471 );
lv_obj_set_y( ui_Button6, 127 );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Button6, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( ui_Button6, &ui_img_3_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
   if (ui_Screen4) lv_obj_del(ui_Screen4);

// NULL screen variables
ui_Screen4= NULL;
ui_Slider1= NULL;
ui_Label8= NULL;
ui_Container1= NULL;
ui_Roller1= NULL;
ui_Roller2= NULL;
ui_Roller3= NULL;
ui_Roller4= NULL;
ui_Roller5= NULL;
ui_Label9= NULL;
ui_Label10= NULL;
ui_Button5= NULL;
ui_Button6= NULL;

}
