// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

