// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: LlamadoEnfermeria

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Slider1;
extern void ui_event_ImgButton1( lv_event_t * e);
extern lv_obj_t *ui_ImgButton1;
extern void ui_event_ImgButton2( lv_event_t * e);
extern lv_obj_t *ui_ImgButton2;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Roller1;
extern lv_obj_t *ui_Roller2;
extern lv_obj_t *ui_Roller3;
extern lv_obj_t *ui_Roller4;
extern lv_obj_t *ui_Roller5;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

